name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: seth-aung
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push snake
        run: |
          git config user.name "seth-aung"
          git config user.email "your-email@example.com"
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake"
          git push
