name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: seth-aung
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and Push Snake
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "seth-aung"
          git config --global user.email "sattaung18101988@gmail.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/seth-aung/seth-aung.git
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake" || echo "No changes to commit"
          git push origin main
