name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # every day at midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@v3
        with:
          github_user_name: seth-aung
          outputs: |
            dist/github-contribution-grid-snake.svg
      - name: Push snake
        run: |
          git config --global user.name "seth-aung"
          git config --global user.email "sattaung18101988@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/seth-aung/seth-aung.git
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake"
          git push
